version: 2.1
jobs:
  install:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - v1-dependencies-{{ checksum "package.json" }}
            # Find the most recently generated cache used from any branch
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm instal
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      # run tests!
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy at Netlify
          command: npm run deploy
workflows:
  build_deploy:
    jobs:
      - install
      - deploy
          requires:
            - install
# version: 2.1
# jobs:
#   install:
#     docker:
#       - image: circleci/node:10.16.0
#     steps:
#       - checkout
#       # cache dependencies
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#       # if cache is not found, install dependencies
#       - run:
#           name: Install dependencies
#           command: |
#             npm install
#       # save dependencies to cache
#       - save_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#           paths:
#             - node_modules
#   test:
#     docker:
#       - image: circleci/node:10.16.0
#     steps:
#       -run:
#         name: Run tests
#         command: |
#           npm run test
#   build:
#     docker:
#       - image: circleci/node:10.16.0
#     steps:
#       - run:
#           name: Build project
#           command: |
#             npm run build
#   deploy:
#     docker:
#       - image: circleci/node:10.16.0
#     steps:
#       - run:
#           name: Deploy project
#           command: |
#             npm run deploy
# workflows:
#   version: 2
#   build-test-deploy:
#     jobs:
#       - install
#       - test:
#           requires:
#             - install
#       - build:
#           requires:
#             - test
#       - deploy:
#           requires:
#             - build
