version: 2.1
jobs:
  install:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      # cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # if cache is not found, install dependencies
      - run:
          name: Install dependencies
          command: npm install
      # save dependencies to cache
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    machine:
      image: ubuntu-1604:201903-01
    docker:
      - image: circleci/node:10.16.0
    steps:
      -run:
        name: Run tests
        command: npm run test
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - run:
          name: Build project
          command: npm run build
  deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - run:
          name: Deploy project
          command: npm run deploy
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
